### ISSUE TITLE
Regular transfers are added to the encrypted_amount_table

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-reference-wallet-android#56]
**Bug Description**
When sending a normal (non-encrypted) transfer from the mobile wallet, a row is added to the `encrypted_amount_table`, with the transaction hash and the amount of the transfer. But normal transfers are unrelated to encrypted amounts, and I assume that it is a bug that they are added to this table as they would never be used in the context of checking the values of encrypted amounts.

**Steps to Reproduce**
1. Send a transfer from the mobile wallet.
2. Click the transaction and copy the `Transaction hash`.
3. Find the row in the `encrypted_amount_table` with the hash found in step 2.

**Expected Result**
Transfers that are not encrypted are not added to the `encrypted_amount_table`.

**Actual Result**
Transfers that are not encrypted show up in the `encrypted_amount_table`.

**Versions**
- Software Version `1.0.14`

**Comment by XOOPsoft** [comment]
The row added to the encrypted_amount_table when sending regular non-encrypted transfers is just for caching.
It doesn't need to be there, but it doesn't do any harm.
So I have agreed with Jens Ager Sørensen from Concordium that it is not worth spending time on changing and testing this issue.
Therefore the issue is closed.
