### ISSUE TITLE
Users are getting stuck on the last Notabene page

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#73]
**Bug Description**

Users are getting stuck on the last page of the Notabene flow, the one with the "Your data is being verified", while showing a loading animation (see screenshot). 

So far it only seems to be happening in the Android wallet, and some users had more luck with the Android version of the CryptoX wallet. The CryptoX wallet is a third party wallet based on our reference implementation, but it is based on an earlier version of our app. Maybe something has changed in our app since? It could also just be luck of the draw, we can't know for sure.

![image](https://user-images.githubusercontent.com/76045015/145373888-e42314ac-404c-4b0f-9d34-46c0aea553b6.png)

We got some info from some of the affected users:

User 1:
Phone model: Galaxy Z Fold3 5G
Android version: Version 11
Wallet version: 1. 0. 16
Other wallets: Nope

User 2:
Phone Model is Samsung A02S 4gb RAM 64gb Storage
Android version is Android 11
Wallet Version 1.0.16
Other wallets: I don't have either Concordium Testnet or CryptoX wallet installed. But I have Concordium mobile wallet installed. I have other crypto wallets like Trust Wallet, TronLink Pro, Blockchain Wallet, Binance Wallet and Atomic Wallet installed on my phone.

User 3:
Phone Model : Huawei P20
Android version 10
Wallet Version : 1.0.16
Other wallets: No

User 4:
Xiaomi Redmi 9
Android 11 RP1A.200720.011
1.0.16
Other wallets: All of them, also other wallets - cosmostation, trust wallet

User 5:
Tecno Pop 5
Android version 10
Concordium Wallet version 1.0.16
Other wallets: Yes, Bitkeep, Trust, metamask Enjin, and algo wallets

**Comment by concordium-cl** [comment]
For completeness, I want to add @td202 slack comments here as well: 

"I think it's likely to be caused by the app failing to parse the redirect URL. This is because in some of the failing cases, users are presented with the option to choose which application to open the URL in, which means the page is trying to do the redirect. It's just the app isn't processing it correctly.

This is the code that does the parsing, which looks like it could be a bit sketchy, though I don't see an immediate problem:
[](https://github.com/Concordium/concordium-reference-wallet-android/blob/b19fbc77021d9f2e55cd386086c5f3f0083f99e1/app/src/main/java/com/concordium/wallet/ui/identity/identityproviderwebview/IdentityProviderWebviewActivity.kt#L191)

Unless #code_uri= can occur more than once in the returned URL"

**Comment by concordium-cl** [comment]
We haven't experienced the issue ourselves and therefore have to await users' reports, if it is not solved.
